# Generated by Django 5.1.4 on 2024-12-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=100)),
                ("access", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
